apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: unae0yyqa-java-springboot
  janus-idp.io/tekton: unae0yyqa-java-springboot
  backstage.io/kubernetes-id: unae0yyqa-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: unae0yyqa-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
